ignoredBuiltDependencies:
  - '@bufbuild/buf'
  - grpc
  - protobufjs
  - protoc

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@nestjs/core'
  - classic-level
  - grpc
  - protobufjs
  - protoc

overrides:
  '@cmts-dev/carmentis-sdk': link:../../../Users/arnau/AppData/Local/pnpm/global/5/node_modules/@cmts-dev/carmentis-sdk
