// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: cometbft/services/version/v1/version_service.proto

/* eslint-disable */

export const protobufPackage = "cometbft.services.version.v1";
