// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: cometbft/services/version/v1/version_service.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { GetVersionRequest, GetVersionResponse } from "./version";

export const protobufPackage = "cometbft.services.version.v1";

/**
 * VersionService simply provides version information about the node and the
 * protocols it uses.
 *
 * The intention with this service is to offer a stable interface through which
 * clients can access version information. This means that the version of the
 * service should be kept stable at v1, with GetVersionResponse evolving only
 * in non-breaking ways.
 */
export interface VersionService {
  /**
   * GetVersion retrieves version information about the node and the protocols
   * it implements.
   */
  GetVersion(request: GetVersionRequest): Promise<GetVersionResponse>;
}

export const VersionServiceServiceName = "cometbft.services.version.v1.VersionService";
export class VersionServiceClientImpl implements VersionService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || VersionServiceServiceName;
    this.rpc = rpc;
    this.GetVersion = this.GetVersion.bind(this);
  }
  GetVersion(request: GetVersionRequest): Promise<GetVersionResponse> {
    const data = GetVersionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetVersion", data);
    return promise.then((data) => GetVersionResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}
