// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: google/protobuf/cpp_features.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb";

export interface CppFeatures {
  /**
   * Whether or not to treat an enum field as closed.  This option is only
   * applicable to enum fields, and will be removed in the future.  It is
   * consistent with the legacy behavior of using proto3 enum types for proto2
   * fields.
   */
  legacy_closed_enum?: boolean | undefined;
  string_type?: CppFeatures_StringType | undefined;
  enum_name_uses_string_view?: boolean | undefined;
}

export enum CppFeatures_StringType {
  STRING_TYPE_UNKNOWN = 0,
  VIEW = 1,
  CORD = 2,
  STRING = 3,
  UNRECOGNIZED = -1,
}

export function cppFeatures_StringTypeFromJSON(object: any): CppFeatures_StringType {
  switch (object) {
    case 0:
    case "STRING_TYPE_UNKNOWN":
      return CppFeatures_StringType.STRING_TYPE_UNKNOWN;
    case 1:
    case "VIEW":
      return CppFeatures_StringType.VIEW;
    case 2:
    case "CORD":
      return CppFeatures_StringType.CORD;
    case 3:
    case "STRING":
      return CppFeatures_StringType.STRING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CppFeatures_StringType.UNRECOGNIZED;
  }
}

export function cppFeatures_StringTypeToJSON(object: CppFeatures_StringType): string {
  switch (object) {
    case CppFeatures_StringType.STRING_TYPE_UNKNOWN:
      return "STRING_TYPE_UNKNOWN";
    case CppFeatures_StringType.VIEW:
      return "VIEW";
    case CppFeatures_StringType.CORD:
      return "CORD";
    case CppFeatures_StringType.STRING:
      return "STRING";
    case CppFeatures_StringType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseCppFeatures(): CppFeatures {
  return { legacy_closed_enum: false, string_type: 0, enum_name_uses_string_view: false };
}

export const CppFeatures: MessageFns<CppFeatures> = {
  encode(message: CppFeatures, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legacy_closed_enum !== undefined && message.legacy_closed_enum !== false) {
      writer.uint32(8).bool(message.legacy_closed_enum);
    }
    if (message.string_type !== undefined && message.string_type !== 0) {
      writer.uint32(16).int32(message.string_type);
    }
    if (message.enum_name_uses_string_view !== undefined && message.enum_name_uses_string_view !== false) {
      writer.uint32(24).bool(message.enum_name_uses_string_view);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CppFeatures {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCppFeatures();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.legacy_closed_enum = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.string_type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.enum_name_uses_string_view = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CppFeatures {
    return {
      legacy_closed_enum: isSet(object.legacy_closed_enum) ? globalThis.Boolean(object.legacy_closed_enum) : false,
      string_type: isSet(object.string_type) ? cppFeatures_StringTypeFromJSON(object.string_type) : 0,
      enum_name_uses_string_view: isSet(object.enum_name_uses_string_view)
        ? globalThis.Boolean(object.enum_name_uses_string_view)
        : false,
    };
  },

  toJSON(message: CppFeatures): unknown {
    const obj: any = {};
    if (message.legacy_closed_enum !== undefined && message.legacy_closed_enum !== false) {
      obj.legacy_closed_enum = message.legacy_closed_enum;
    }
    if (message.string_type !== undefined && message.string_type !== 0) {
      obj.string_type = cppFeatures_StringTypeToJSON(message.string_type);
    }
    if (message.enum_name_uses_string_view !== undefined && message.enum_name_uses_string_view !== false) {
      obj.enum_name_uses_string_view = message.enum_name_uses_string_view;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CppFeatures>, I>>(base?: I): CppFeatures {
    return CppFeatures.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CppFeatures>, I>>(object: I): CppFeatures {
    const message = createBaseCppFeatures();
    message.legacy_closed_enum = object.legacy_closed_enum ?? false;
    message.string_type = object.string_type ?? 0;
    message.enum_name_uses_string_view = object.enum_name_uses_string_view ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
