// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: google/protobuf/java_features.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb";

export interface JavaFeatures {
  /**
   * Whether or not to treat an enum field as closed.  This option is only
   * applicable to enum fields, and will be removed in the future.  It is
   * consistent with the legacy behavior of using proto3 enum types for proto2
   * fields.
   */
  legacy_closed_enum?: boolean | undefined;
  utf8_validation?:
    | JavaFeatures_Utf8Validation
    | undefined;
  /**
   * Whether to use the old default outer class name scheme, or the new feature
   * which adds a "Proto" suffix to the outer class name.
   *
   * Users will not be able to set this option, because we removed it in the
   * same edition that it was introduced. But we use it to determine which
   * naming scheme to use for outer class name defaults.
   */
  use_old_outer_classname_default?: boolean | undefined;
}

/**
 * The UTF8 validation strategy to use.  See go/editions-utf8-validation for
 * more information on this feature.
 */
export enum JavaFeatures_Utf8Validation {
  /** UTF8_VALIDATION_UNKNOWN - Invalid default, which should never be used. */
  UTF8_VALIDATION_UNKNOWN = 0,
  /**
   * DEFAULT - Respect the UTF8 validation behavior specified by the global
   * utf8_validation feature.
   */
  DEFAULT = 1,
  /**
   * VERIFY - Verifies UTF8 validity overriding the global utf8_validation
   * feature. This represents the legacy java_string_check_utf8 option.
   */
  VERIFY = 2,
  UNRECOGNIZED = -1,
}

export function javaFeatures_Utf8ValidationFromJSON(object: any): JavaFeatures_Utf8Validation {
  switch (object) {
    case 0:
    case "UTF8_VALIDATION_UNKNOWN":
      return JavaFeatures_Utf8Validation.UTF8_VALIDATION_UNKNOWN;
    case 1:
    case "DEFAULT":
      return JavaFeatures_Utf8Validation.DEFAULT;
    case 2:
    case "VERIFY":
      return JavaFeatures_Utf8Validation.VERIFY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return JavaFeatures_Utf8Validation.UNRECOGNIZED;
  }
}

export function javaFeatures_Utf8ValidationToJSON(object: JavaFeatures_Utf8Validation): string {
  switch (object) {
    case JavaFeatures_Utf8Validation.UTF8_VALIDATION_UNKNOWN:
      return "UTF8_VALIDATION_UNKNOWN";
    case JavaFeatures_Utf8Validation.DEFAULT:
      return "DEFAULT";
    case JavaFeatures_Utf8Validation.VERIFY:
      return "VERIFY";
    case JavaFeatures_Utf8Validation.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseJavaFeatures(): JavaFeatures {
  return { legacy_closed_enum: false, utf8_validation: 0, use_old_outer_classname_default: false };
}

export const JavaFeatures: MessageFns<JavaFeatures> = {
  encode(message: JavaFeatures, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legacy_closed_enum !== undefined && message.legacy_closed_enum !== false) {
      writer.uint32(8).bool(message.legacy_closed_enum);
    }
    if (message.utf8_validation !== undefined && message.utf8_validation !== 0) {
      writer.uint32(16).int32(message.utf8_validation);
    }
    if (message.use_old_outer_classname_default !== undefined && message.use_old_outer_classname_default !== false) {
      writer.uint32(32).bool(message.use_old_outer_classname_default);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JavaFeatures {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJavaFeatures();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.legacy_closed_enum = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.utf8_validation = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.use_old_outer_classname_default = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JavaFeatures {
    return {
      legacy_closed_enum: isSet(object.legacy_closed_enum) ? globalThis.Boolean(object.legacy_closed_enum) : false,
      utf8_validation: isSet(object.utf8_validation) ? javaFeatures_Utf8ValidationFromJSON(object.utf8_validation) : 0,
      use_old_outer_classname_default: isSet(object.use_old_outer_classname_default)
        ? globalThis.Boolean(object.use_old_outer_classname_default)
        : false,
    };
  },

  toJSON(message: JavaFeatures): unknown {
    const obj: any = {};
    if (message.legacy_closed_enum !== undefined && message.legacy_closed_enum !== false) {
      obj.legacy_closed_enum = message.legacy_closed_enum;
    }
    if (message.utf8_validation !== undefined && message.utf8_validation !== 0) {
      obj.utf8_validation = javaFeatures_Utf8ValidationToJSON(message.utf8_validation);
    }
    if (message.use_old_outer_classname_default !== undefined && message.use_old_outer_classname_default !== false) {
      obj.use_old_outer_classname_default = message.use_old_outer_classname_default;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JavaFeatures>, I>>(base?: I): JavaFeatures {
    return JavaFeatures.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JavaFeatures>, I>>(object: I): JavaFeatures {
    const message = createBaseJavaFeatures();
    message.legacy_closed_enum = object.legacy_closed_enum ?? false;
    message.utf8_validation = object.utf8_validation ?? 0;
    message.use_old_outer_classname_default = object.use_old_outer_classname_default ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
