// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: gogoproto/gogo.proto

/* eslint-disable */

export const protobufPackage = "gogoproto";
