// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: cometbft/services/pruning/v1/pruning.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cometbft.services.pruning.v1";

/** SetBlockRetainHeightRequest sets the retain height for blocks. */
export interface SetBlockRetainHeightRequest {
  height: number;
}

/** SetBlockRetainHeightResponse is empty. */
export interface SetBlockRetainHeightResponse {
}

/** GetBlockRetainHeightRequest is a request for the retain height. */
export interface GetBlockRetainHeightRequest {
}

/** GetBlockRetainHeightResponse returns the retain height for blocks. */
export interface GetBlockRetainHeightResponse {
  /** The retain height set by the application. */
  app_retain_height: number;
  /**
   * The retain height set via the pruning service (e.g. by the data
   * companion) specifically for blocks.
   */
  pruning_service_retain_height: number;
}

/** SetBlockResultsRetainHeightRequest sets the retain height for block results. */
export interface SetBlockResultsRetainHeightRequest {
  height: number;
}

/** SetBlockResultsRetainHeightResponse is empty. */
export interface SetBlockResultsRetainHeightResponse {
}

/** GetBlockResultsRetainHeightRequest is a request for the retain height. */
export interface GetBlockResultsRetainHeightRequest {
}

/** GetBlockResultsRetainHeightResponse returns the retain height for block results. */
export interface GetBlockResultsRetainHeightResponse {
  /**
   * The retain height set by the pruning service (e.g. by the data
   * companion) specifically for block results.
   */
  pruning_service_retain_height: number;
}

/** SetTxIndexerRetainHeightRequest sets the retain height for the tx indexer. */
export interface SetTxIndexerRetainHeightRequest {
  height: number;
}

/** SetTxIndexerRetainHeightResponse is empty. */
export interface SetTxIndexerRetainHeightResponse {
}

/** GetTxIndexerRetainHeightRequest is a request for the retain height. */
export interface GetTxIndexerRetainHeightRequest {
}

/** GetTxIndexerRetainHeightResponse returns the retain height for the tx indexer. */
export interface GetTxIndexerRetainHeightResponse {
  height: number;
}

/** SetBlockIndexerRetainHeightRequest sets the retain height for the block indexer. */
export interface SetBlockIndexerRetainHeightRequest {
  height: number;
}

/** SetBlockIndexerRetainHeightResponse is empty. */
export interface SetBlockIndexerRetainHeightResponse {
}

/** GetBlockIndexerRetainHeightRequest is a request for the retain height. */
export interface GetBlockIndexerRetainHeightRequest {
}

/** GetBlockIndexerRetainHeightResponse returns the retain height for the block indexer. */
export interface GetBlockIndexerRetainHeightResponse {
  height: number;
}

function createBaseSetBlockRetainHeightRequest(): SetBlockRetainHeightRequest {
  return { height: 0 };
}

export const SetBlockRetainHeightRequest: MessageFns<SetBlockRetainHeightRequest> = {
  encode(message: SetBlockRetainHeightRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.height !== 0) {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetBlockRetainHeightRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.height = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetBlockRetainHeightRequest {
    return { height: isSet(object.height) ? globalThis.Number(object.height) : 0 };
  },

  toJSON(message: SetBlockRetainHeightRequest): unknown {
    const obj: any = {};
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetBlockRetainHeightRequest>, I>>(base?: I): SetBlockRetainHeightRequest {
    return SetBlockRetainHeightRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetBlockRetainHeightRequest>, I>>(object: I): SetBlockRetainHeightRequest {
    const message = createBaseSetBlockRetainHeightRequest();
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseSetBlockRetainHeightResponse(): SetBlockRetainHeightResponse {
  return {};
}

export const SetBlockRetainHeightResponse: MessageFns<SetBlockRetainHeightResponse> = {
  encode(_: SetBlockRetainHeightResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetBlockRetainHeightResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetBlockRetainHeightResponse {
    return {};
  },

  toJSON(_: SetBlockRetainHeightResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetBlockRetainHeightResponse>, I>>(base?: I): SetBlockRetainHeightResponse {
    return SetBlockRetainHeightResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetBlockRetainHeightResponse>, I>>(_: I): SetBlockRetainHeightResponse {
    const message = createBaseSetBlockRetainHeightResponse();
    return message;
  },
};

function createBaseGetBlockRetainHeightRequest(): GetBlockRetainHeightRequest {
  return {};
}

export const GetBlockRetainHeightRequest: MessageFns<GetBlockRetainHeightRequest> = {
  encode(_: GetBlockRetainHeightRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockRetainHeightRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetBlockRetainHeightRequest {
    return {};
  },

  toJSON(_: GetBlockRetainHeightRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockRetainHeightRequest>, I>>(base?: I): GetBlockRetainHeightRequest {
    return GetBlockRetainHeightRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockRetainHeightRequest>, I>>(_: I): GetBlockRetainHeightRequest {
    const message = createBaseGetBlockRetainHeightRequest();
    return message;
  },
};

function createBaseGetBlockRetainHeightResponse(): GetBlockRetainHeightResponse {
  return { app_retain_height: 0, pruning_service_retain_height: 0 };
}

export const GetBlockRetainHeightResponse: MessageFns<GetBlockRetainHeightResponse> = {
  encode(message: GetBlockRetainHeightResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.app_retain_height !== 0) {
      writer.uint32(8).uint64(message.app_retain_height);
    }
    if (message.pruning_service_retain_height !== 0) {
      writer.uint32(16).uint64(message.pruning_service_retain_height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockRetainHeightResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.app_retain_height = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pruning_service_retain_height = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockRetainHeightResponse {
    return {
      app_retain_height: isSet(object.app_retain_height) ? globalThis.Number(object.app_retain_height) : 0,
      pruning_service_retain_height: isSet(object.pruning_service_retain_height)
        ? globalThis.Number(object.pruning_service_retain_height)
        : 0,
    };
  },

  toJSON(message: GetBlockRetainHeightResponse): unknown {
    const obj: any = {};
    if (message.app_retain_height !== 0) {
      obj.app_retain_height = Math.round(message.app_retain_height);
    }
    if (message.pruning_service_retain_height !== 0) {
      obj.pruning_service_retain_height = Math.round(message.pruning_service_retain_height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockRetainHeightResponse>, I>>(base?: I): GetBlockRetainHeightResponse {
    return GetBlockRetainHeightResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockRetainHeightResponse>, I>>(object: I): GetBlockRetainHeightResponse {
    const message = createBaseGetBlockRetainHeightResponse();
    message.app_retain_height = object.app_retain_height ?? 0;
    message.pruning_service_retain_height = object.pruning_service_retain_height ?? 0;
    return message;
  },
};

function createBaseSetBlockResultsRetainHeightRequest(): SetBlockResultsRetainHeightRequest {
  return { height: 0 };
}

export const SetBlockResultsRetainHeightRequest: MessageFns<SetBlockResultsRetainHeightRequest> = {
  encode(message: SetBlockResultsRetainHeightRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.height !== 0) {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetBlockResultsRetainHeightRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockResultsRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.height = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetBlockResultsRetainHeightRequest {
    return { height: isSet(object.height) ? globalThis.Number(object.height) : 0 };
  },

  toJSON(message: SetBlockResultsRetainHeightRequest): unknown {
    const obj: any = {};
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetBlockResultsRetainHeightRequest>, I>>(
    base?: I,
  ): SetBlockResultsRetainHeightRequest {
    return SetBlockResultsRetainHeightRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetBlockResultsRetainHeightRequest>, I>>(
    object: I,
  ): SetBlockResultsRetainHeightRequest {
    const message = createBaseSetBlockResultsRetainHeightRequest();
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseSetBlockResultsRetainHeightResponse(): SetBlockResultsRetainHeightResponse {
  return {};
}

export const SetBlockResultsRetainHeightResponse: MessageFns<SetBlockResultsRetainHeightResponse> = {
  encode(_: SetBlockResultsRetainHeightResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetBlockResultsRetainHeightResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockResultsRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetBlockResultsRetainHeightResponse {
    return {};
  },

  toJSON(_: SetBlockResultsRetainHeightResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetBlockResultsRetainHeightResponse>, I>>(
    base?: I,
  ): SetBlockResultsRetainHeightResponse {
    return SetBlockResultsRetainHeightResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetBlockResultsRetainHeightResponse>, I>>(
    _: I,
  ): SetBlockResultsRetainHeightResponse {
    const message = createBaseSetBlockResultsRetainHeightResponse();
    return message;
  },
};

function createBaseGetBlockResultsRetainHeightRequest(): GetBlockResultsRetainHeightRequest {
  return {};
}

export const GetBlockResultsRetainHeightRequest: MessageFns<GetBlockResultsRetainHeightRequest> = {
  encode(_: GetBlockResultsRetainHeightRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockResultsRetainHeightRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockResultsRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetBlockResultsRetainHeightRequest {
    return {};
  },

  toJSON(_: GetBlockResultsRetainHeightRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockResultsRetainHeightRequest>, I>>(
    base?: I,
  ): GetBlockResultsRetainHeightRequest {
    return GetBlockResultsRetainHeightRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockResultsRetainHeightRequest>, I>>(
    _: I,
  ): GetBlockResultsRetainHeightRequest {
    const message = createBaseGetBlockResultsRetainHeightRequest();
    return message;
  },
};

function createBaseGetBlockResultsRetainHeightResponse(): GetBlockResultsRetainHeightResponse {
  return { pruning_service_retain_height: 0 };
}

export const GetBlockResultsRetainHeightResponse: MessageFns<GetBlockResultsRetainHeightResponse> = {
  encode(message: GetBlockResultsRetainHeightResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pruning_service_retain_height !== 0) {
      writer.uint32(8).uint64(message.pruning_service_retain_height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockResultsRetainHeightResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockResultsRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pruning_service_retain_height = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockResultsRetainHeightResponse {
    return {
      pruning_service_retain_height: isSet(object.pruning_service_retain_height)
        ? globalThis.Number(object.pruning_service_retain_height)
        : 0,
    };
  },

  toJSON(message: GetBlockResultsRetainHeightResponse): unknown {
    const obj: any = {};
    if (message.pruning_service_retain_height !== 0) {
      obj.pruning_service_retain_height = Math.round(message.pruning_service_retain_height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockResultsRetainHeightResponse>, I>>(
    base?: I,
  ): GetBlockResultsRetainHeightResponse {
    return GetBlockResultsRetainHeightResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockResultsRetainHeightResponse>, I>>(
    object: I,
  ): GetBlockResultsRetainHeightResponse {
    const message = createBaseGetBlockResultsRetainHeightResponse();
    message.pruning_service_retain_height = object.pruning_service_retain_height ?? 0;
    return message;
  },
};

function createBaseSetTxIndexerRetainHeightRequest(): SetTxIndexerRetainHeightRequest {
  return { height: 0 };
}

export const SetTxIndexerRetainHeightRequest: MessageFns<SetTxIndexerRetainHeightRequest> = {
  encode(message: SetTxIndexerRetainHeightRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.height !== 0) {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetTxIndexerRetainHeightRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTxIndexerRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.height = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTxIndexerRetainHeightRequest {
    return { height: isSet(object.height) ? globalThis.Number(object.height) : 0 };
  },

  toJSON(message: SetTxIndexerRetainHeightRequest): unknown {
    const obj: any = {};
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTxIndexerRetainHeightRequest>, I>>(base?: I): SetTxIndexerRetainHeightRequest {
    return SetTxIndexerRetainHeightRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTxIndexerRetainHeightRequest>, I>>(
    object: I,
  ): SetTxIndexerRetainHeightRequest {
    const message = createBaseSetTxIndexerRetainHeightRequest();
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseSetTxIndexerRetainHeightResponse(): SetTxIndexerRetainHeightResponse {
  return {};
}

export const SetTxIndexerRetainHeightResponse: MessageFns<SetTxIndexerRetainHeightResponse> = {
  encode(_: SetTxIndexerRetainHeightResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetTxIndexerRetainHeightResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTxIndexerRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetTxIndexerRetainHeightResponse {
    return {};
  },

  toJSON(_: SetTxIndexerRetainHeightResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTxIndexerRetainHeightResponse>, I>>(
    base?: I,
  ): SetTxIndexerRetainHeightResponse {
    return SetTxIndexerRetainHeightResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTxIndexerRetainHeightResponse>, I>>(
    _: I,
  ): SetTxIndexerRetainHeightResponse {
    const message = createBaseSetTxIndexerRetainHeightResponse();
    return message;
  },
};

function createBaseGetTxIndexerRetainHeightRequest(): GetTxIndexerRetainHeightRequest {
  return {};
}

export const GetTxIndexerRetainHeightRequest: MessageFns<GetTxIndexerRetainHeightRequest> = {
  encode(_: GetTxIndexerRetainHeightRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTxIndexerRetainHeightRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTxIndexerRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetTxIndexerRetainHeightRequest {
    return {};
  },

  toJSON(_: GetTxIndexerRetainHeightRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTxIndexerRetainHeightRequest>, I>>(base?: I): GetTxIndexerRetainHeightRequest {
    return GetTxIndexerRetainHeightRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTxIndexerRetainHeightRequest>, I>>(_: I): GetTxIndexerRetainHeightRequest {
    const message = createBaseGetTxIndexerRetainHeightRequest();
    return message;
  },
};

function createBaseGetTxIndexerRetainHeightResponse(): GetTxIndexerRetainHeightResponse {
  return { height: 0 };
}

export const GetTxIndexerRetainHeightResponse: MessageFns<GetTxIndexerRetainHeightResponse> = {
  encode(message: GetTxIndexerRetainHeightResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.height !== 0) {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTxIndexerRetainHeightResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTxIndexerRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.height = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTxIndexerRetainHeightResponse {
    return { height: isSet(object.height) ? globalThis.Number(object.height) : 0 };
  },

  toJSON(message: GetTxIndexerRetainHeightResponse): unknown {
    const obj: any = {};
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTxIndexerRetainHeightResponse>, I>>(
    base?: I,
  ): GetTxIndexerRetainHeightResponse {
    return GetTxIndexerRetainHeightResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTxIndexerRetainHeightResponse>, I>>(
    object: I,
  ): GetTxIndexerRetainHeightResponse {
    const message = createBaseGetTxIndexerRetainHeightResponse();
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseSetBlockIndexerRetainHeightRequest(): SetBlockIndexerRetainHeightRequest {
  return { height: 0 };
}

export const SetBlockIndexerRetainHeightRequest: MessageFns<SetBlockIndexerRetainHeightRequest> = {
  encode(message: SetBlockIndexerRetainHeightRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.height !== 0) {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetBlockIndexerRetainHeightRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockIndexerRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.height = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetBlockIndexerRetainHeightRequest {
    return { height: isSet(object.height) ? globalThis.Number(object.height) : 0 };
  },

  toJSON(message: SetBlockIndexerRetainHeightRequest): unknown {
    const obj: any = {};
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetBlockIndexerRetainHeightRequest>, I>>(
    base?: I,
  ): SetBlockIndexerRetainHeightRequest {
    return SetBlockIndexerRetainHeightRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetBlockIndexerRetainHeightRequest>, I>>(
    object: I,
  ): SetBlockIndexerRetainHeightRequest {
    const message = createBaseSetBlockIndexerRetainHeightRequest();
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseSetBlockIndexerRetainHeightResponse(): SetBlockIndexerRetainHeightResponse {
  return {};
}

export const SetBlockIndexerRetainHeightResponse: MessageFns<SetBlockIndexerRetainHeightResponse> = {
  encode(_: SetBlockIndexerRetainHeightResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetBlockIndexerRetainHeightResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockIndexerRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetBlockIndexerRetainHeightResponse {
    return {};
  },

  toJSON(_: SetBlockIndexerRetainHeightResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetBlockIndexerRetainHeightResponse>, I>>(
    base?: I,
  ): SetBlockIndexerRetainHeightResponse {
    return SetBlockIndexerRetainHeightResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetBlockIndexerRetainHeightResponse>, I>>(
    _: I,
  ): SetBlockIndexerRetainHeightResponse {
    const message = createBaseSetBlockIndexerRetainHeightResponse();
    return message;
  },
};

function createBaseGetBlockIndexerRetainHeightRequest(): GetBlockIndexerRetainHeightRequest {
  return {};
}

export const GetBlockIndexerRetainHeightRequest: MessageFns<GetBlockIndexerRetainHeightRequest> = {
  encode(_: GetBlockIndexerRetainHeightRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockIndexerRetainHeightRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockIndexerRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetBlockIndexerRetainHeightRequest {
    return {};
  },

  toJSON(_: GetBlockIndexerRetainHeightRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockIndexerRetainHeightRequest>, I>>(
    base?: I,
  ): GetBlockIndexerRetainHeightRequest {
    return GetBlockIndexerRetainHeightRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockIndexerRetainHeightRequest>, I>>(
    _: I,
  ): GetBlockIndexerRetainHeightRequest {
    const message = createBaseGetBlockIndexerRetainHeightRequest();
    return message;
  },
};

function createBaseGetBlockIndexerRetainHeightResponse(): GetBlockIndexerRetainHeightResponse {
  return { height: 0 };
}

export const GetBlockIndexerRetainHeightResponse: MessageFns<GetBlockIndexerRetainHeightResponse> = {
  encode(message: GetBlockIndexerRetainHeightResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.height !== 0) {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockIndexerRetainHeightResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockIndexerRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.height = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockIndexerRetainHeightResponse {
    return { height: isSet(object.height) ? globalThis.Number(object.height) : 0 };
  },

  toJSON(message: GetBlockIndexerRetainHeightResponse): unknown {
    const obj: any = {};
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockIndexerRetainHeightResponse>, I>>(
    base?: I,
  ): GetBlockIndexerRetainHeightResponse {
    return GetBlockIndexerRetainHeightResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockIndexerRetainHeightResponse>, I>>(
    object: I,
  ): GetBlockIndexerRetainHeightResponse {
    const message = createBaseGetBlockIndexerRetainHeightResponse();
    message.height = object.height ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
