// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: cometbft/services/pruning/v1/service.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import {
  GetBlockIndexerRetainHeightRequest,
  GetBlockIndexerRetainHeightResponse,
  GetBlockResultsRetainHeightRequest,
  GetBlockResultsRetainHeightResponse,
  GetBlockRetainHeightRequest,
  GetBlockRetainHeightResponse,
  GetTxIndexerRetainHeightRequest,
  GetTxIndexerRetainHeightResponse,
  SetBlockIndexerRetainHeightRequest,
  SetBlockIndexerRetainHeightResponse,
  SetBlockResultsRetainHeightRequest,
  SetBlockResultsRetainHeightResponse,
  SetBlockRetainHeightRequest,
  SetBlockRetainHeightResponse,
  SetTxIndexerRetainHeightRequest,
  SetTxIndexerRetainHeightResponse,
} from "./pruning";

export const protobufPackage = "cometbft.services.pruning.v1";

/**
 * PruningService provides privileged access to specialized pruning
 * functionality on the CometBFT node to help control node storage.
 */
export interface PruningService {
  /**
   * SetBlockRetainHeightRequest indicates to the node that it can safely
   * prune all block data up to the specified retain height.
   *
   * The lower of this retain height and that set by the application in its
   * Commit response will be used by the node to determine which heights' data
   * can be pruned.
   */
  SetBlockRetainHeight(request: SetBlockRetainHeightRequest): Promise<SetBlockRetainHeightResponse>;
  /**
   * GetBlockRetainHeight returns information about the retain height
   * parameters used by the node to influence block retention/pruning.
   */
  GetBlockRetainHeight(request: GetBlockRetainHeightRequest): Promise<GetBlockRetainHeightResponse>;
  /**
   * SetBlockResultsRetainHeightRequest indicates to the node that it can
   * safely prune all block results data up to the specified height.
   *
   * The node will always store the block results for the latest height to
   * help facilitate crash recovery.
   */
  SetBlockResultsRetainHeight(
    request: SetBlockResultsRetainHeightRequest,
  ): Promise<SetBlockResultsRetainHeightResponse>;
  /**
   * GetBlockResultsRetainHeight returns information about the retain height
   * parameters used by the node to influence block results retention/pruning.
   */
  GetBlockResultsRetainHeight(
    request: GetBlockResultsRetainHeightRequest,
  ): Promise<GetBlockResultsRetainHeightResponse>;
  /**
   * SetTxIndexerRetainHeightRequest indicates to the node that it can safely
   * prune all tx indices up to the specified retain height.
   */
  SetTxIndexerRetainHeight(request: SetTxIndexerRetainHeightRequest): Promise<SetTxIndexerRetainHeightResponse>;
  /**
   * GetTxIndexerRetainHeight returns information about the retain height
   * parameters used by the node to influence TxIndexer pruning
   */
  GetTxIndexerRetainHeight(request: GetTxIndexerRetainHeightRequest): Promise<GetTxIndexerRetainHeightResponse>;
  /**
   * SetBlockIndexerRetainHeightRequest indicates to the node that it can safely
   * prune all block indices up to the specified retain height.
   */
  SetBlockIndexerRetainHeight(
    request: SetBlockIndexerRetainHeightRequest,
  ): Promise<SetBlockIndexerRetainHeightResponse>;
  /**
   * GetBlockIndexerRetainHeight returns information about the retain height
   * parameters used by the node to influence BlockIndexer pruning
   */
  GetBlockIndexerRetainHeight(
    request: GetBlockIndexerRetainHeightRequest,
  ): Promise<GetBlockIndexerRetainHeightResponse>;
}

export const PruningServiceServiceName = "cometbft.services.pruning.v1.PruningService";
export class PruningServiceClientImpl implements PruningService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || PruningServiceServiceName;
    this.rpc = rpc;
    this.SetBlockRetainHeight = this.SetBlockRetainHeight.bind(this);
    this.GetBlockRetainHeight = this.GetBlockRetainHeight.bind(this);
    this.SetBlockResultsRetainHeight = this.SetBlockResultsRetainHeight.bind(this);
    this.GetBlockResultsRetainHeight = this.GetBlockResultsRetainHeight.bind(this);
    this.SetTxIndexerRetainHeight = this.SetTxIndexerRetainHeight.bind(this);
    this.GetTxIndexerRetainHeight = this.GetTxIndexerRetainHeight.bind(this);
    this.SetBlockIndexerRetainHeight = this.SetBlockIndexerRetainHeight.bind(this);
    this.GetBlockIndexerRetainHeight = this.GetBlockIndexerRetainHeight.bind(this);
  }
  SetBlockRetainHeight(request: SetBlockRetainHeightRequest): Promise<SetBlockRetainHeightResponse> {
    const data = SetBlockRetainHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetBlockRetainHeight", data);
    return promise.then((data) => SetBlockRetainHeightResponse.decode(new BinaryReader(data)));
  }

  GetBlockRetainHeight(request: GetBlockRetainHeightRequest): Promise<GetBlockRetainHeightResponse> {
    const data = GetBlockRetainHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBlockRetainHeight", data);
    return promise.then((data) => GetBlockRetainHeightResponse.decode(new BinaryReader(data)));
  }

  SetBlockResultsRetainHeight(
    request: SetBlockResultsRetainHeightRequest,
  ): Promise<SetBlockResultsRetainHeightResponse> {
    const data = SetBlockResultsRetainHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetBlockResultsRetainHeight", data);
    return promise.then((data) => SetBlockResultsRetainHeightResponse.decode(new BinaryReader(data)));
  }

  GetBlockResultsRetainHeight(
    request: GetBlockResultsRetainHeightRequest,
  ): Promise<GetBlockResultsRetainHeightResponse> {
    const data = GetBlockResultsRetainHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBlockResultsRetainHeight", data);
    return promise.then((data) => GetBlockResultsRetainHeightResponse.decode(new BinaryReader(data)));
  }

  SetTxIndexerRetainHeight(request: SetTxIndexerRetainHeightRequest): Promise<SetTxIndexerRetainHeightResponse> {
    const data = SetTxIndexerRetainHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetTxIndexerRetainHeight", data);
    return promise.then((data) => SetTxIndexerRetainHeightResponse.decode(new BinaryReader(data)));
  }

  GetTxIndexerRetainHeight(request: GetTxIndexerRetainHeightRequest): Promise<GetTxIndexerRetainHeightResponse> {
    const data = GetTxIndexerRetainHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTxIndexerRetainHeight", data);
    return promise.then((data) => GetTxIndexerRetainHeightResponse.decode(new BinaryReader(data)));
  }

  SetBlockIndexerRetainHeight(
    request: SetBlockIndexerRetainHeightRequest,
  ): Promise<SetBlockIndexerRetainHeightResponse> {
    const data = SetBlockIndexerRetainHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetBlockIndexerRetainHeight", data);
    return promise.then((data) => SetBlockIndexerRetainHeightResponse.decode(new BinaryReader(data)));
  }

  GetBlockIndexerRetainHeight(
    request: GetBlockIndexerRetainHeightRequest,
  ): Promise<GetBlockIndexerRetainHeightResponse> {
    const data = GetBlockIndexerRetainHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBlockIndexerRetainHeight", data);
    return promise.then((data) => GetBlockIndexerRetainHeightResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}
