// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: cometbft/services/pruning/v1/service.proto

/* eslint-disable */

export const protobufPackage = "cometbft.services.pruning.v1";
