// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: cometbft/rpc/grpc/v1beta2/types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ResponseCheckTx, ResponseDeliverTx } from "../../../abci/v1beta2/types";
import { RequestBroadcastTx, RequestPing, ResponsePing } from "../v1beta1/types";

export const protobufPackage = "cometbft.rpc.grpc.v1beta2";

/** ResponseBroadcastTx is a response of broadcasting the transaction. */
export interface ResponseBroadcastTx {
  checkTx: ResponseCheckTx | undefined;
  deliverTx: ResponseDeliverTx | undefined;
}

function createBaseResponseBroadcastTx(): ResponseBroadcastTx {
  return { checkTx: undefined, deliverTx: undefined };
}

export const ResponseBroadcastTx: MessageFns<ResponseBroadcastTx> = {
  encode(message: ResponseBroadcastTx, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.checkTx !== undefined) {
      ResponseCheckTx.encode(message.checkTx, writer.uint32(10).fork()).join();
    }
    if (message.deliverTx !== undefined) {
      ResponseDeliverTx.encode(message.deliverTx, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResponseBroadcastTx {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponseBroadcastTx();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.checkTx = ResponseCheckTx.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deliverTx = ResponseDeliverTx.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponseBroadcastTx {
    return {
      checkTx: isSet(object.checkTx) ? ResponseCheckTx.fromJSON(object.checkTx) : undefined,
      deliverTx: isSet(object.deliverTx) ? ResponseDeliverTx.fromJSON(object.deliverTx) : undefined,
    };
  },

  toJSON(message: ResponseBroadcastTx): unknown {
    const obj: any = {};
    if (message.checkTx !== undefined) {
      obj.checkTx = ResponseCheckTx.toJSON(message.checkTx);
    }
    if (message.deliverTx !== undefined) {
      obj.deliverTx = ResponseDeliverTx.toJSON(message.deliverTx);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResponseBroadcastTx>, I>>(base?: I): ResponseBroadcastTx {
    return ResponseBroadcastTx.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResponseBroadcastTx>, I>>(object: I): ResponseBroadcastTx {
    const message = createBaseResponseBroadcastTx();
    message.checkTx = (object.checkTx !== undefined && object.checkTx !== null)
      ? ResponseCheckTx.fromPartial(object.checkTx)
      : undefined;
    message.deliverTx = (object.deliverTx !== undefined && object.deliverTx !== null)
      ? ResponseDeliverTx.fromPartial(object.deliverTx)
      : undefined;
    return message;
  },
};

/** BroadcastAPI is an API for broadcasting transactions. */
export interface BroadcastAPI {
  /** Ping the connection. */
  Ping(request: RequestPing): Promise<ResponsePing>;
  /** BroadcastTx broadcasts the transaction. */
  BroadcastTx(request: RequestBroadcastTx): Promise<ResponseBroadcastTx>;
}

export const BroadcastAPIServiceName = "cometbft.rpc.grpc.v1beta2.BroadcastAPI";
export class BroadcastAPIClientImpl implements BroadcastAPI {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || BroadcastAPIServiceName;
    this.rpc = rpc;
    this.Ping = this.Ping.bind(this);
    this.BroadcastTx = this.BroadcastTx.bind(this);
  }
  Ping(request: RequestPing): Promise<ResponsePing> {
    const data = RequestPing.encode(request).finish();
    const promise = this.rpc.request(this.service, "Ping", data);
    return promise.then((data) => ResponsePing.decode(new BinaryReader(data)));
  }

  BroadcastTx(request: RequestBroadcastTx): Promise<ResponseBroadcastTx> {
    const data = RequestBroadcastTx.encode(request).finish();
    const promise = this.rpc.request(this.service, "BroadcastTx", data);
    return promise.then((data) => ResponseBroadcastTx.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
