// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: cometbft/services/block/v1/block_service.proto

/* eslint-disable */

export const protobufPackage = "cometbft.services.block.v1";
