// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: cometbft/services/block/v1/block_service.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { GetByHeightRequest, GetByHeightResponse, GetLatestHeightRequest, GetLatestHeightResponse } from "./block";

export const protobufPackage = "cometbft.services.block.v1";

/** BlockService provides information about blocks */
export interface BlockService {
  /** GetBlock retrieves the block information at a particular height. */
  GetByHeight(request: GetByHeightRequest): Promise<GetByHeightResponse>;
  /**
   * GetLatestHeight returns a stream of the latest block heights committed by
   * the network. This is a long-lived stream that is only terminated by the
   * server if an error occurs. The caller is expected to handle such
   * disconnections and automatically reconnect.
   */
  GetLatestHeight(request: GetLatestHeightRequest): Observable<GetLatestHeightResponse>;
}

export const BlockServiceServiceName = "cometbft.services.block.v1.BlockService";
export class BlockServiceClientImpl implements BlockService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || BlockServiceServiceName;
    this.rpc = rpc;
    this.GetByHeight = this.GetByHeight.bind(this);
    this.GetLatestHeight = this.GetLatestHeight.bind(this);
  }
  GetByHeight(request: GetByHeightRequest): Promise<GetByHeightResponse> {
    const data = GetByHeightRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetByHeight", data);
    return promise.then((data) => GetByHeightResponse.decode(new BinaryReader(data)));
  }

  GetLatestHeight(request: GetLatestHeightRequest): Observable<GetLatestHeightResponse> {
    const data = GetLatestHeightRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "GetLatestHeight", data);
    return result.pipe(map((data) => GetLatestHeightResponse.decode(new BinaryReader(data))));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}
