// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "hero/hero.proto" (package "hero", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { HeroesService } from "./hero";
import type { EchoResponse } from "../cometbft/abci/v1/types";
import type { EchoRequest } from "../cometbft/abci/v1/types";
import type { Message } from "./hero";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Hero } from "./hero";
import type { HeroById } from "./hero";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service hero.HeroesService
 */
export interface IHeroesServiceClient {
    /**
     * @generated from protobuf rpc: FindOne(hero.HeroById) returns (hero.Hero);
     */
    findOne(input: HeroById, options?: RpcOptions): UnaryCall<HeroById, Hero>;
    /**
     * @generated from protobuf rpc: Echo(hero.Message) returns (hero.Message);
     */
    echo(input: Message, options?: RpcOptions): UnaryCall<Message, Message>;
    /**
     * @generated from protobuf rpc: Echo2(cometbft.abci.v1.EchoRequest) returns (cometbft.abci.v1.EchoResponse);
     */
    echo2(input: EchoRequest, options?: RpcOptions): UnaryCall<EchoRequest, EchoResponse>;
}
/**
 * @generated from protobuf service hero.HeroesService
 */
export class HeroesServiceClient implements IHeroesServiceClient, ServiceInfo {
    typeName = HeroesService.typeName;
    methods = HeroesService.methods;
    options = HeroesService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: FindOne(hero.HeroById) returns (hero.Hero);
     */
    findOne(input: HeroById, options?: RpcOptions): UnaryCall<HeroById, Hero> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HeroById, Hero>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Echo(hero.Message) returns (hero.Message);
     */
    echo(input: Message, options?: RpcOptions): UnaryCall<Message, Message> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Message, Message>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Echo2(cometbft.abci.v1.EchoRequest) returns (cometbft.abci.v1.EchoResponse);
     */
    echo2(input: EchoRequest, options?: RpcOptions): UnaryCall<EchoRequest, EchoResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<EchoRequest, EchoResponse>("unary", this._transport, method, opt, input);
    }
}
