export const LevelDbTable: Record<string, number> = {
    CHAIN_INFORMATION: 0x00,
    DATA_FILE: 0x01,
    VB_RADIX: 0x02,
    TOKEN_RADIX: 0x03,
    BLOCK_INFORMATION: 0x04,
    BLOCK_CONTENT: 0x05,
    MICROBLOCK_VB_INFORMATION: 0x06,
    MICROBLOCK_STORAGE: 0x07,
    VIRTUAL_BLOCKCHAIN_STATE:  0x08,
    ACCOUNT_STATE: 0x09,
    ACCOUNT_HISTORY: 0x0a,
    ACCOUNT_BY_PUBLIC_KEY: 0x0b,
    ACCOUNTS_WITH_VESTING_LOCKS: 0x0c,
    ESCROWS: 0x0d,
    VALIDATOR_NODE_BY_ADDRESS: 0x0e,
    PROTOCOL_INDEX: 0x0f,
    ACCOUNTS_INDEX: 0x10,
    VALIDATOR_NODES_INDEX: 0x11,
    ORGANIZATIONS_INDEX: 0x12,
    APPLICATIONS_INDEX: 0x13,
}

const encoder = new TextEncoder();
export const ChainInformationIndex = {
    CHAIN_INFORMATION_KEY: encoder.encode("CHAIN_INFORMATION")
}